### ISSUE TITLE
Add option to include ValidationContext secrets

### ISSUE THREAD

**Issue by pehala** [3scale-ops/marin3r#169]
Currently, only [TLSCertificates](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-tlscertificate) can be specified in the secrets section of EnvoyConfig, it would be great if also [CertificateValidationContext](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-certificatevalidationcontext) secret were allowed.

The absence of this feature means that dynamic mTLS (with custom CA for validation) doesn't currently work

**Comment by roivaz** [comment]
Example of defining a CA within a `type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret` proto:

```yaml
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_sds
    validation_context:
      trusted_ca:
        filename: /certs/cacert.pem
```

which is slightly different from how a certificate is defined:

```yaml
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: tls_sds
    tls_certificate:
      certificate_chain:
        filename: /certs/sds_cert.pem
      private_key:
        filename: /certs/sds_key.pem
```

Right now only the second type is generated, to add support for the first type there are a couple of options:

1. Just add a "type" field to the secret resources in the EnvoyConfig to generate a secret of the "CA type"
2. Add a generic mechanism to generate secrets for envoy sds, where you provide a template that fetches the secret values from a generic k8s Secret. There are more types of secrets in envoy's sds protocol that certificate and ca, and this mechanism would cover them all.

Also a combination of both options would be good, option 1 for easy CA managemenr for validation contexts, and option 2 for a generic mechanism that potentially cover other uses of sds.

**Comment by roivaz** [comment]
Example of defining a CA within a `type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret` proto:

```yaml
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_sds
    validation_context:
      trusted_ca:
        filename: /certs/cacert.pem
```

which is slightly different from how a certificate is defined:

```yaml
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: tls_sds
    tls_certificate:
      certificate_chain:
        filename: /certs/sds_cert.pem
      private_key:
        filename: /certs/sds_key.pem
```

Right now only the second type is generated, to add support for the first type there are a couple of options:

1. Just add a "type" field to the secret resources in the EnvoyConfig to generate a secret of the "CA type"
2. Add a generic mechanism to generate secrets for envoy sds, where you provide a template that fetches the secret values from a generic k8s Secret. There are more types of secrets in envoy's sds protocol that certificate and ca, and this mechanism would cover them all.

Also a combination of both options would be good, option 1 for easy CA managemenr for validation contexts, and option 2 for a generic mechanism that potentially cover other uses of sds.

**Comment by roivaz** [comment]
Example usage:

```yaml
apiVersion: marin3r.3scale.net/v1alpha1
kind: EnvoyConfig
metadata:
  name: config
  namespace: test
spec:
  nodeID: proxy
  resources:
    - type: secret
      generateFromTlsSecret: ca
      blueprint: validationContext
```
