### ISSUE TITLE
Update EnvoyConfig and EnvoyConfigRevision secret namespace required field

### ISSUE THREAD

**Issue by slopezz** [3scale-ops/marin3r#61]
Now that `DiscoveryService` is namespace scope since https://github.com/3scale/marin3r/pull/60, there is no need to specify the namespace on the secret ref spec:

```yaml
  envoyResources:
    secrets:
      - name: kuard-certificate
        ref:
          name: kuard-certificate
          namespace: default  ### This one
```

Because being DS a namespace scope resource, means that secret must live on the NS where DS/EC are deployed, so having that required namespace field is redundant and not needed to be added by the end customer defining the EC.

Documentation, examples... will need to be updated reflecting that change.
